{"name": "Verify Login functionality with data driven testing", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <testCases.test_login_ddt.Test_Login_DDT object at 0x110c8b590>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"5f657c480b9c1747258c235d1ac42ec0\")>\nuser_cred = {'password': 'password123', 'username': 'admin1@admin.com'}\n\n    @pytest.mark.parametrize(\"user_cred\",read_credentials_from_file(file_path=file_path))\n    @allure.title(\"Verify Login functionality with data driven testing\")\n    @allure.testcase(\"TC003\")\n    @allure.tag(\"Smoke\")\n    def test_login_ddt(self, setup,user_cred):\n        try:\n            username = user_cred[\"username\"]\n            password = user_cred[\"password\"]\n            self.logger.info(\"****** Verifying login test ******\")\n            self.driver = setup\n            self.driver.get(self.baseURL)\n            self.lp = LoginPage(self.driver)\n            self.lp.setUserName(username)\n            self.lp.setPassword(password)\n            self.lp.clickLogin()\n>           assert self.driver.title == \"Dashboard / nopCommerce administration\"\nE           AssertionError: assert 'Your store. Login' == 'Dashboard / ...dministration'\nE             \nE             - Dashboard / nopCommerce administration\nE             + Your store. Login\n\ntestCases/test_login_ddt.py:47: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <testCases.test_login_ddt.Test_Login_DDT object at 0x110c8b590>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"5f657c480b9c1747258c235d1ac42ec0\")>\nuser_cred = {'password': 'password123', 'username': 'admin1@admin.com'}\n\n    @pytest.mark.parametrize(\"user_cred\",read_credentials_from_file(file_path=file_path))\n    @allure.title(\"Verify Login functionality with data driven testing\")\n    @allure.testcase(\"TC003\")\n    @allure.tag(\"Smoke\")\n    def test_login_ddt(self, setup,user_cred):\n        try:\n            username = user_cred[\"username\"]\n            password = user_cred[\"password\"]\n            self.logger.info(\"****** Verifying login test ******\")\n            self.driver = setup\n            self.driver.get(self.baseURL)\n            self.lp = LoginPage(self.driver)\n            self.lp.setUserName(username)\n            self.lp.setPassword(password)\n            self.lp.clickLogin()\n            assert self.driver.title == \"Dashboard / nopCommerce administration\"\n            self.logger.info(\"****** Login test passed ******\")\n            self.driver.close()\n        except AssertionError:\n            allure.attach(self.driver.get_screenshot_as_png(), attachment_type=AttachmentType.PNG)\n            self.logger.error(\"****** Login test is failed ******\")\n            self.driver.close()\n>           assert False\nE           assert False\n\ntestCases/test_login_ddt.py:54: AssertionError"}, "attachments": [{"source": "b0888274-cee4-4efc-8b31-846aa449080d-attachment.png", "type": "image/png"}, {"name": "log", "source": "a11e06c5-025b-4c95-a3cd-91f52b62c0ab-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "user_cred", "value": "{'username': 'admin1@admin.com', 'password': 'password123'}"}], "start": 1715740928608, "stop": 1715740930337, "uuid": "28c38cd3-f4ca-4857-bc1d-af40589b8224", "historyId": "e622ea7672b078f3b5482a28df8304db", "testCaseId": "f334beae98f69ea6d4b0d28ba8dd6c51", "fullName": "testCases.test_login_ddt.Test_Login_DDT#test_login_ddt", "labels": [{"name": "tag", "value": "Smoke"}, {"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_login_ddt"}, {"name": "subSuite", "value": "Test_Login_DDT"}, {"name": "host", "value": "Kaustubhs-MacBook-Pro-2.local"}, {"name": "thread", "value": "33634-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_login_ddt"}], "links": [{"type": "tms", "url": "TC003", "name": "TC003"}]}